version: "3.8"

services:
  flaskapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask-app:latest
    container_name: flask-app
    ports:
      - "5000:80"
    restart: unless-stopped
